### ISSUE TITLE
Package is not the same as the `promise-throttle` package on npm

### ISSUE THREAD

**Issue by Mesoptier** [rhashimoto/promise-throttle#1]
Have you perhaps published this package under a different name, or maybe not at all?

**Comment by AbeCole** [comment]
Yes this package is not called 'promise-throttle' on NPM and I wasn't able to find a matching NPM library. However there are some similar packages with the same call blueprint.

I'd suggest: [p-throttle](https://www.npmjs.com/package/p-throttle)

**Comment by rhashimoto** [comment]
I don't have any current plans to publish on npm. I wrote it because I needed it myself. Javascript is not my primary language.
