### ISSUE TITLE
I'd like to fork, maintain and publish it. What do you think?

### ISSUE THREAD

**Issue by tiagostutz** [rhashimoto/promise-throttle#2]
Hi @rhashimoto ! I've just used this lib here and worked like a charm. Thanks for that, was really useful for me.

I saw in #1 that you don't have plans to maintain this project or publish a npm package, so I'd like to know whether it would be OK if I made a hard fork of this repo, publish this lib in npm and maintain the code.

If you agree with that, I'd ask you to put a MIT license here and to put a reference on README for the repo I will create.

On my repo I'll put a reference for you and your code in the top of the README and the project license will be MIT.

Any thoughts on that? 

Thanks!

**Comment by rhashimoto** [comment]
Done. Full blessings to fork.

**Comment by tiagostutz** [comment]
Thanks a lot!
Started it here: https://github.com/tiagostutz/fetch-throttle

Best regards!
